language: node_js
node_js:
  - 6
  - 8
  - 10

notifications:
  email: false
  slack:
    secure: VsyHmsSqaV/CtMj2obgwMzFDlTDiu5ZVJX/2sLD/rACtdLGxgDZjmESUz79Q8PvU45/BrLiGNn2ydsoxceZgtmGzkyYHIVwQD3xgZpj3FEC6Wj0XAFCH2RaG4ia7CHOIq+sBvTT79oQYsZxpX6MOXpIeQa4aZdJvvU4HJajm3OWNZAeiOjiF2Xqx7WrZkhpcYFnZcNJP2cCyQqb6koncCujwO5u1oM8BnmHbAATA/cGOwChH44VWvU736ZUV95E3ELjTUvjvHCdCAAY/CubhuxKf4koamuETeY02yC48oP+ddoxnqoXW8I9Y4jv069JLeJfvi+0Kv0NZ5jJjnFp+1qvFpfkfOJTs0aMqSFIupjXtBU5OP3zpWNK+1knPgbpI07mH52FV3AAYSwdUzDeAWkOv549w9V+1v6PZEdP8g23quji0k/DmF6ZK51FT4mqq+fx+N1n0puoGam6RIvi3l/5a9bG8lPAM/1oLbonUVzvGBNz9Ksc/MdVIhixeWWWIgkP2j/JqwC72gbcSICEtDp2pe8fM4ftynI88QASXiQMQJ/100L1AJvvnWAkNNCD8QlsYrE9CIzezG2vqKJyX+/H5Hi8ww4TW5tqTFPV/df3OTCNefBzMrUy0jP8m/Wc2wsF7Iar/kXyxIpfD52ZxjcRmK3PLDnrA9ip4WF+0Wq4=

cache:
  directories:
    - "$HOME/.npm"
