language: node_js
node_js:
  - 6
  - 8
  - 10
script:
  - node_modules/.bin/travis-github-status lint jest codeclimate
notifications:
  email: false
  slack:
    secure: lZ3SYVnT4y65wE+YShCt6pi7TJG+FKIEuZRBknGh9ksmr/thd1YIfwzTmn2O/9ALhsZFe/H3CwC2nopNT+/ZXZ5u/gRG58vByfOSvVMBcPN+8qAIZEeU6urHLMBTyHnm1QEMJQRlQ2wXTW3LvW40/4DJ+aSluaW00Zh5rke9NydfH+xPteEO1nLt6xCRbBVNokby1LkZReGGTlNo9jzCd/gZhfJlpzwmqRB8WxaWoI5lcke/5N7LxWzLh3HS0wp5rGTyAwYRk+viH+LeKalmHQymgm2cU8eQBdPNNCNjZzyFLV7/XOXrsblp9h994ahc5G9vSB3xsbO+gio1F16l9Bka5HlmjTRLMo9dYjaMfhMPs2SAVuhoIEDTnZnDp6bDmGrDe0JQvma0CABBLpVoTQSmwSyAIVOBYNesdXjd/F6jnrpKi3DlSGYb4yJ9p1QWSWtN2OtRXSQxQjkIPe9qrOJguc6smP/5zFlDCzX01IyQlu4zJQIHaGKQk2Triq1QEdDWOHg2BXA4O6ISlWp5U+9dEp2BEj8WN1F4Egj4IKwD2y5H18b864+2og7txa3Iz48oawWmDrbOf6Lm06DEhj5HSy8MfygnZhH06GHUJD8kQ4Adg6lYtZDA89DT+1I9BtRfQttmlWbxOwlBGFRWRO8zC/gKRyvywzZjHoOjhw4=
cache:
  directories:
    - $HOME/.npm
